version: '3'
services:
  lunarlang:
    build: .
    volumes:
      - "../:/lunarlang"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    stdin_open: true
    tty: true
    working_dir: "/lunarlang"
